### Get all products
GET http://localhost:3000/products

### Get product by id
GET http://localhost:3000/products/2

### Create a new productp
POST http://localhost:3000/products/
Content-Type: application/json

{
    "name": "plant",
    "price": 15
}

### Update a product
PUT http://localhost:3000/products/2

{
    "name": "old book",
    "price": 130
}


### Delete a product
DELETE http://localhost:3000/products/2

##########################

### *********    USERS   ***********

### Get  users
GET http://localhost:3000/users

### Get users por id
GET http://localhost:3000/users/1

### Update  users
PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "first_name": "laudy2",
    "last_name": "nava",
    "username": "lau",
    "password": "12345",
    "email": "lau@",
    "admin": "1"
}

### Delete users
DELETE http://localhost:3000/users/1


### *********    CATEGORIES   ***********

### Get  categories
GET http://localhost:3000/categories

### Get categories id
GET http://localhost:3000/categories/1


### *********    lOGIN   ***********

### Login fallido
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "boo",
    "password": 123
}

### Login exitoso
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "laudy",
    "password": 321
}

### Login fallido
GET http://localhost:3000/logout

### Login fallido
GET http://localhost:3000/login-fallido

### Ruta protegida
GET http://localhost:3000/ruta-protegida